// <auto-generated />
using System;
using CitiesManager.WebAPI.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230621151600_IzmenaStruktureTabeleCity_DopunaPolja")]
    partial class IzmenaStruktureTabeleCity_DopunaPolja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CitiesManager.Core.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfFoundation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = new Guid("643b309f-d8c1-4b85-b48a-285cfdd69114"),
                            CityHistory = "...",
                            CityName = "Зрењанин",
                            DateOfFoundation = new DateTime(1500, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            Population = 90000,
                            ZipCode = "23000"
                        },
                        new
                        {
                            CityID = new Guid("459a76f0-f918-4965-b197-d8e0a3edeb27"),
                            CityHistory = "...",
                            CityName = "Београд",
                            DateOfFoundation = new DateTime(1500, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            Population = 220000,
                            ZipCode = "11000"
                        },
                        new
                        {
                            CityID = new Guid("b6f78464-4403-4210-949f-236d28753fdd"),
                            CityHistory = "...",
                            CityName = "Нови Сад",
                            DateOfFoundation = new DateTime(1500, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "...",
                            Population = 45000,
                            ZipCode = "21000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
